Erosionlunar.MITSistema/Controllers/PartesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Erosionlunar.MITSistema.Entities;
using Erosionlunar.MITSistema.Models;
using Mysqlx.Prepare;
using MimeKit;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Security.Cryptography;
using System.Security.Policy;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
using Humanizer;
using System.Text;
using System.IO.Compression;
using NuGet.Packaging;
using Org.BouncyCastle.Asn1;

namespace Erosionlunar.MITSistema.Controllers
{
    public class PartesController : Controller
    {
        private readonly MyAppContext _context;
        private string pathToPartes;
        private string pathToBaseMDB;
        public PartesController(MyAppContext context)
        {
            _context = context;
            var elPathRaw = _context.MainFrame.FirstOrDefault(c => c.IdMainFrame == 1);
            var BaseMDB = _context.MainFrame.FirstOrDefault(c => c.IdMainFrame == 13);
            pathToPartes = elPathRaw?.Valores ?? string.Empty;
            pathToBaseMDB = BaseMDB?.Valores ?? string.Empty;
        }

        // GET: Partes
        public ActionResult Index()
        {
            return View();
        }

        //PartesMO2 POST
        private PreParteFixModel getPreParteFromId(string? idPreParte)
        {
            int elIdPreParte = -1;
            if(idPreParte != null)
            {
                elIdPreParte = stringToInt(idPreParte);
            }
            var elPreParteRaw = _context.PreParte.AsNoTracking().FirstOrDefault(c => c.idPreParte == stringToInt(idPreParte));
            PreParteFixModel elPreParte = null;
            if(elPreParteRaw != null)
            {
                elPreParte = new PreParteFixModel(elPreParteRaw);
            }
            return elPreParte;
        }
        private void prepararParte(PartesFixModel elParte, int numeroP, int idEmpresa)
        {
            elParte.setIdParte(_context.Partes.Max(c => c.idParte + 1));
            elParte.setNumeroP(numeroP);
            elParte.setIdEmpresa(idEmpresa);
            elParte.setIdTipoParte(2);
            elParte.setComentario("");
            elParte.setFechaP(DateTime.Now);
            var laEmpresa = _context.Empresas.AsNoTracking().FirstOrDefault(c => c.IdEmpresa == elParte.idEmpresaV);
            elParte.setNombresE(laEmpresa);
            var destDire = _context.InformacionEmpresa.AsNoTracking().FirstOrDefault(c => c.IdTipoInformacion == 2 && c.IdEmpresa == elParte.idEmpresaV);
            elParte.setDD(destDire);
            var losMails = _context.MailsDeParte.AsNoTracking().Where(c => c.numeroP == numeroP.ToString()).ToList();
            foreach (MailsDeParteModel unMailDeParte in losMails)
            {
                var laInfoMail = _context.InformacionEmpresa.AsNoTracking().FirstOrDefault(c => c.IdInformacionEmpresa == unMailDeParte.idNombreYMail);
                elParte.addMailInfoDirs(laInfoMail);
            }
        }
        private List<string> getStringFromRequest(HttpRequest elRequest, string nombreInput)
        {
            bool esNull = false;
            var laLista = new List<string>();

            for (int i = 0; i < 1000 & esNull == false; i++)
            {
                string? elInput = elRequest.Form[nombreInput + $"[{i}]"];
                if (elInput != null)
                {
                    laLista.Add(elInput);
                }
            }
            return laLista;
        }
        private List<int> getIntFromRequest(HttpRequest elRequest, string nombreInput)
        {
            bool esNull = false;
            var laLista = new List<int>();

            for (int i = 0; i < 1000 & esNull == false; i++)
            {
                string? elInput = elRequest.Form[nombreInput + $"[{i}]"];
                if (elInput != null)
                {
                    laLista.Add(stringToInt(elInput));
                }
            }
            return laLista;
        }
        private List<MediosOpticosFixModel> crearMOs(List<int> losMOIdArch, List<int> losMOGrupo, List<string> losMONombre, List<string> losPath, List<int> losIdArch, int idParte)
        {
            var losMO = new List<MediosOpticosFixModel>();
            var idMaxIdMO = _context.MediosOpticos.Max(c => c.IdMedioOptico);
            idMaxIdMO++;
            for (int i = 0; i < losMOIdArch.Count; i++)
            {
                int elIdSeleccionado = losMOIdArch[i];
                if (losMOGrupo[i] == 0) // Si el grupo es 0 crea un nuevoMO
                {
                    var nuevoMO = new MediosOpticosFixModel();
                    nuevoMO.setIdMO(idMaxIdMO);
                    idMaxIdMO++;
                    nuevoMO.setIdParte(idParte);
                    nuevoMO.setNombreMO(losMONombre[i]);
                    nuevoMO.setRamificacion(0);
                    nuevoMO.setEsRamaActiva(1);
                    nuevoMO.initArchivos();
                    //Trae el Archivo de BD
                    var elArchivo = _context.Archivos.AsNoTracking().FirstOrDefault(c => c.IdArchivo == losIdArch[i]);
                    var elArchivoFix = new ArchivosFixModel(elArchivo);
                    elArchivoFix.setUbicacion(losPath[i]);
                    nuevoMO.addArchivo(elArchivoFix);
                    losMO.Add(nuevoMO);
                }
                if (losMOGrupo[i] != 0)
                {
                    int indiceDeMO = 0;
                    for (int j = 0; j < losIdArch.Count; j++)
                    {
                        if (losMOGrupo[j] == 0) { indiceDeMO++; }
                        if (losIdArch[j] == losMOGrupo[i])
                        {
                            //Trae el Archivo de BD
                            var elArchivo = _context.Archivos.AsNoTracking().FirstOrDefault(c => c.IdArchivo == losIdArch[i]);
                            var elArchivoFix = new ArchivosFixModel(elArchivo);
                            elArchivoFix.setUbicacion(losPath[i]);
                            losMO[indiceDeMO].addArchivo(elArchivoFix);
                        }
                    }
                }
            }
            return losMO;
        }
        private bool verificarFechasMO(List<MediosOpticosFixModel> losMO)
        {
            bool estanBien = true;
            foreach (MediosOpticosFixModel unMO in losMO)
            {
                var unaFecha = _context.archivosFechas.AsNoTracking().FirstOrDefault(c => c.idArchivo == unMO.getByIndiceId(0));
                var fechaDate = unaFecha.fecha;
                for (int i = 1; i < unMO.getCantidadArchivos(); i++)
                {
                    var otraFecha = _context.archivosFechas.AsNoTracking().FirstOrDefault(c => c.idArchivo == unMO.getByIndiceId(0));
                    var fechaDateOtra = otraFecha.fecha;
                    if (fechaDate != fechaDateOtra)
                    {
                        estanBien = false;
                        break;
                    }
                }
                unMO.setPeriodoMO(fechaDate);
            }
            return estanBien;
        }
        private void crearCheckSum(string checkSumPath, List<ArchivosFixModel> losArchivos)
        {
            System.IO.File.WriteAllText(checkSumPath, "");
            foreach (ArchivosFixModel unArchivo in losArchivos)
            {
                System.IO.File.AppendAllText(checkSumPath, Path.GetFileName(unArchivo.ubicacionInicialV) + "||" + unArchivo.HashAV + "\n");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PartesMO2()
        {
            //Preparando PreParte
            var elPreParte = getPreParteFromId(Request.Form["elIdPreParte"]);
            if (elPreParte == null) { return View("MyError", $"No se encuentra el PreParte de ID: {Request.Form["elIdPreParte"]}."); }
            //Variables
            
            //Preparando Parte
            var elParte = new PartesFixModel();
            try
            {
                prepararParte(elParte, elPreParte.numeroPV, elPreParte.idEmpresaV);
            }
            catch(Exception ex)
            {
                return View("MyError", "Problema en la preparación del Parte." + ex.InnerException);
            }
            //Preparando Input
            var losIdArch = getIntFromRequest(Request, "idArchivo");
            var losPath = getStringFromRequest(Request, "ubicacion");
            var losMOIdArch = getIntFromRequest(Request, "MOID"); ;
            var losMOGrupo = getIntFromRequest(Request, "MOGrupo"); ;
            var losMONombre = getStringFromRequest(Request, "MONombre");
            bool sonDelMismoTamaño = losIdArch.Count == losPath.Count && losPath.Count == losMOIdArch.Count && losMOIdArch.Count == losMOGrupo.Count && losMOGrupo.Count == losMONombre.Count;
            if (!sonDelMismoTamaño) { return View("MyError", $"Error en tamaño variables input."); }
            //Crear MOs
            var losMO = new List<MediosOpticosFixModel>();
            try
            {
                losMO = crearMOs(losMOIdArch, losMOGrupo, losMONombre, losPath, losIdArch, elParte.idParteV);
            }
            catch(Exception ex)
            {
                return View("MyError", "Problema en la Creacion Medios Opticos." + ex.InnerException);
            }

            //Chequear Fecha MO
            bool tienenFechasBienMOs = true;
            try
            {
                tienenFechasBienMOs = verificarFechasMO(losMO);
            }
            catch(Exception ex)
            {
                return View("MyError", "Problema en la verificacion Fechas Medios Opticos." + ex.InnerException);
            }
            if(!tienenFechasBienMOs)
            {

Erosionlunar.MITSistema/Views/Partes/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center container">
    <div class="row">
        <a class="btn btn-primary col-md-4 offset-md-4" asp-controller="Partes" asp-action="PartesList">Parte Lista</a>
    </div>
    <div class="row">
        <a class="btn btn-primary col-md-4 offset-md-4" asp-controller="Partes" asp-action="PartesMO">Crear Parte MO</a>
    </div>
</div>

Erosionlunar.MITSistema/Views/Partes/PartesDetail.cshtml
@model Erosionlunar.MITSistema.Models.PartesFixModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Detalles Parte</h1>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.idParteV)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.idParteV)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nombreEV) 
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nombreEV)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.numeroPV)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.numeroPV)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPV)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FechaPV)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DestinatariosDireccionV)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DestinatariosDireccionV)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DestinatariosEmailV)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DestinatariosEmailV)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DestinatariosV)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DestinatariosV)
        </dd>
    </dl>
</div>


@for(int i = 0; i< Model.getCantidadMOs(); i++)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Model.getByIndiceNombreMO(i)
                </th>
                <th>
                    @Model.getByIndicePreiodoMO(i)
                </th>
                <th>
                    Folio Inicial
                </th>
                <th>
                    Folio Final
                </th>
                <th>
                    Hash
                </th>
                <th>
                    Asiento Inicial
                </th>
                <th>
                    Asiento Final
                </th>
            </tr>
        </thead>
        @for(int j = 0; j < Model.getQAdeMO(i); j++)
        {
            <tbody>
            <tr>
                <td>
                    @Model.getNLAdeMO(i,j)
                </td>
                <td>
                    @Model.getFAdeMO(i, j)
                </td>
                <td>
                    @Model.getFIAdeMO(i, j)
                </td>
                <td>
                    @Model.getFFAdeMO(i, j)
                </td>
                <td>
                    @Model.getHAdeMO(i, j)
                </td>
                <td>
                    @{
                        string folioI = "-";
                        string folioF = "-";
                    }
                    @if (Model.getAFAdeMO(i, j) > 20)
                    {
                        folioI = @Model.getAIAdeMO(i, j).ToString();
                        folioF = @Model.getAFAdeMO(i, j).ToString();
                    }
                    @folioI
                </td>
                <td>
                    @folioF
                </td>
            </tr>
            </tbody>
        }
    </table>
}

@foreach(string unMensaje in @Model.darMensajesMails())
{
    <p>
        @unMensaje
    </p>
    <hr />
}


<div>
    <a asp-action="PartesEdit" asp-route-id="@Model?.idParteV">Editar</a> |
    <a asp-action="PartesList">Volver a Lista</a>
</div>

Erosionlunar.MITSistema/Views/Partes/PartesEdit.cshtml
@model Erosionlunar.MITSistema.Models.PartesFixModel

@{
    ViewData["Title"] = "Parte Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Editar Parte</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="PartesEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="idParteV" />
            <div class="form-group">
                <label asp-for="idTipoParteV" class="control-label"></label>
                <input asp-for="idTipoParteV" class="form-control" />
                <span asp-validation-for="idTipoParteV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="idEmpresaV" class="control-label"></label>
                <input asp-for="idEmpresaV" class="form-control" />
                <span asp-validation-for="idEmpresaV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numeroPV" class="control-label"></label>
                <input asp-for="numeroPV" class="form-control" />
                <span asp-validation-for="numeroPV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPV" class="control-label"></label>
                <input asp-for="FechaPV" type="date" class="form-control" value="@(Model.FechaPV.ToString("yyyy-MM-dd"))" />
                <span asp-validation-for="FechaPV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ComentarioV" class="control-label"></label>
                <input asp-for="ComentarioV" class="form-control" />
                <span asp-validation-for="ComentarioV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinatariosDireccionV" class="control-label"></label>
                <input asp-for="DestinatariosDireccionV" class="form-control" />
                <span asp-validation-for="DestinatariosDireccionV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinatariosEmailV" class="control-label"></label>
                <input asp-for="DestinatariosEmailV" class="form-control" />
                <span asp-validation-for="DestinatariosEmailV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DestinatariosV" class="control-label"></label>
                <input asp-for="DestinatariosV" class="form-control" />
                <span asp-validation-for="DestinatariosV" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="PartesLista">Volver a Lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Erosionlunar.MITSistema/Views/Partes/PartesList.cshtml
@model IEnumerable<Erosionlunar.MITSistema.Models.PartesFixModel>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.numeroPV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombreCortoEV)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaPV)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.numeroPV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombreCortoEV)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaPV)
                </td>
                <td>
                    <a asp-action="PartesEdit" asp-route-id="@item.idParteV">Editar</a> |
                    <a asp-action="PartesDetail" asp-route-id="@item.idParteV">Detalles</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Erosionlunar.MITSistema/Views/Partes/PartesMO.cshtml
@model List<Erosionlunar.MITSistema.Models.PreParteFixModel>

@{
    ViewData["Title"] = "Parte Creacion Medios Opticos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear Parte</h1>

<hr />

<form asp-action="PartesMO" id="preParteForm" asp-controller="Partes" method="post">
    <input type="submit" value="Continuar" class="btn btn-primary" />
    <table class="table">
        <thead>
            <tr>
                <th>
                    Seleccionar
                </th>
                <th>
                    ID PreParte
                </th>
                <th>
                    Numero Parte
                </th>
                <th>
                    Fecha Recibido
                </th>
                <th>
                    Empresa
                </th>
            </tr>
        </thead>
        <tbody>
            @for(int i = 0; i < Model.Count();i++)
            {
                <tr>
                    <td>
                        <input type="checkbox" class="PreParteCheckbox" data-index="@i" />
                    </td>
                    <td>
                        <input name="idPreParteV" type="text" value="@Model[i].idPreParteV" />
                    </td>
                    <td>
                        <input name="numeroPV" type="text" value="@Model[i].numeroPV" />
                    </td>
                    <td>
                        <input name="fechaRV" type="date" value="@(@Model[i].fechaRecibidoV.ToString("yyyy-MM-dd"))" />
                    </td>
                    <td>
                        <input name="nCortoEV" type="text" value="@Model[i].nCortoEV" />
                        <input name="idEmpresaV" type="hidden" value="@Model[i].idEmpresaV" />
                    </td>
                </tr>
            }
        </tbody>
    </table>        
</form>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        // Select all checkboxes with the class 'carpetaCheckBox'
        const checkboxes = document.querySelectorAll(".PreParteCheckbox");

        checkboxes.forEach(checkbox => {
            checkbox.addEventListener("click", function () {
                // Uncheck all checkboxes except the one that was just clicked
                checkboxes.forEach(cb => {
                    if (cb !== this) cb.checked = false;
                });
            });
        });

        // On form submission, disable all rows except the checked one
        document.getElementById("preParteForm").addEventListener("submit", function (event) {
            checkboxes.forEach(checkbox => {
                const row = checkbox.closest("tr");
                if (!checkbox.checked) {
                    // Disable all inputs in the row if the checkbox is not checked
                    row.querySelectorAll("input").forEach(input => input.disabled = true);
                }
                else {
                    row.querySelectorAll("input").forEach(input => input.disabled = false);
                }
            });
        });
    });
</script>

Erosionlunar.MITSistema/Views/Partes/PartesMO2.cshtml
@model List<Erosionlunar.MITSistema.Models.ArchivosFixModel>

@{
    ViewData["Title"] = "Parte Creacion Medios Opticos 2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Crear Parte 2</h1>

<hr />

<form asp-action="PartesMO2" id="parteForm" asp-controller="Partes" method="post">
    <input type="submit" value="Continuar" class="btn btn-primary" />
    <input type="number" value="@ViewBag.elPreParte.idPreParteV" name="elIdPreParte" />
    <table class="table">
        <thead>
            <tr>
                <th class="col-1">
                    ID archivo
                </th>
                <th class="col-1">
                    Ubicación Archivo
                </th>
                <th class="col-1">
                    MO ID
                </th>
                <th class="col-1">
                    MO Grupo
                </th>
                <th class="col-6">
                    Nombre MO
                </th>
            </tr>
        </thead>
        <tbody>
            @for(int i = 0; i<Model.Count(); i++)
            {
                <tr>
                    <td>
                        <input type="number" name="idArchivo[@i]" value="@Model[i].IdArchivoV" />
                        <p>@Model[i].pesoV MB</p>
                    </td>
                    <td>
                        <input type="text" name="ubicacion[@i]" value="@Model[i].ubicacionInicialV" />
                        <p>@(System.IO.Path.GetFileName(Model[i].ubicacionInicialV))</p>
                    </td>
                    <td>
                        <input type="number" name="MOID[@i]" value="@(i + 1)" />
                    </td>
                    <td>
                        <input type="number" name="MOGrupo[@i]" value="0" />
                    </td>
                    <td>
                        <input type="text" name="MONombre[@i]" value="@Model[i].nombreLibroV" style="width:100%" />
                    </td>
                </tr>
            }
            
        </tbody>
    </table>
</form>